CREATE TABLE IF NOT EXISTS comments(
      id SERIAL PRIMARY KEY,
      text VARCHAR (5000) NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT NOW(),
      task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE ON UPDATE CASCADE
);
