CREATE TABLE IF NOT EXISTS comments(
      id SERIAL PRIMARY KEY,
      text VARCHAR (5000) NOT NULL,
      position INTEGER UNIQUE NOT NULL DEFAULT 0,
      project_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE ON UPDATE CASCADE
);